nonMeatList = [
"beanfeast",
"boca burger",
"eggplant",
"falafel",
"fistulina hepatica",
"gardenburger",
"glamorgan sausage",
"gluten-free vegan meat",
"jackfruit",
"koya-dofu",
"laetiporus",
"leaf protein concentrate",
"lentils",
"lyophyllum decastes",
"mock duck",
"nut roast",
"oncom",
"paneer",
"quorn",
"seitan",
"soy protein",
"soy pulp",
"tempeh",
"textured vegetable protein",
"tofu",
"tofurkey",
"tofurky",
"turtle island foods",
"v-chicken",
"vegetarian bacon",
"vegetarian hot dog",
"veggie burger",
"viana",
"v-meat",
"v-sausage",
"v-turkey",
"wheat gluten"
]