meats = (
    ("pork, chicken, beef"),    #1
    ("basa",
"flounder",
"hake",
"scup",
"smelt",
"rainbow trout",
"hardshell clam",
"blue crab",
"peekytoe crab",
"spanner crab",
"cuttlefish",
"eastern oyster",
"pacific oyster",
"anchovy",
"herring",
"lingcod",
"moi",
"orange roughy",
"atlantic ocean perch",
"lake victoria perch",
"yellow perch",
"european oyster",
"sea urchin",
"atlantic mackerel",
"black sea bass",
"european sea bass",
"hybrid striped bass",
"bream",
"cod",
"drum",
"haddock",
"hoki",
"alaska pollock",
"rockfish",
"pink salmon",
"snapper",
"tilapia",
"turbot",
"walleye",
"lake whitefish",
"wolffish",
"hardshell clam",
"surf clam",
"cockle",
"jonah crab",
"snow crab",
"crayfish",
"bay scallop",
"chinese white shrimp",
"sablefish",
"atlantic salmon",
"coho salmon",
"skate",
"dungeness crab",
"king crab",
"blue mussel",
"greenshell mussel",
"pink shrimp",
"escolar",
"chinook salmon",
"chum salmon",
"american shad",
"arctic char",
"carp",
"catfish",
"dory",
"grouper",
"halibut",
"monkfish",
"pompano",
"dover sole",
"sturgeon",
"tilefish",
"wahoo",
"yellowtail",
"abalone",
"conch",
"stone crab",
"american lobster",
"spiny lobster",
"octopus",
"black tiger shrimp",
"freshwater shrimp",
"gulf shrimp",
"pacific white shrimp",
"squid",
"barramundi",
"cusk",
"dogfish",
"kingklip",
"mahimahi",
"opah",
"mako shark",
"swordfish",
"albacore tuna",
"yellowfin tuna",
"geoduck clam",
"squat lobster",
"sea scallop",
"rock shrimp",
"barracuda",
"chilean sea bass",
"cobia",
"croaker",
"eel",
"blue marlin",
"mullet",
"sockeye salmon",
"bluefin tuna",
),               #2,
    ("ground beef"),            #3
    ("pulled pork"),             #4
    ("Bacon", "Turkey Bacon"),
    ("chicken broth"),
    ("beef broth"),
    ("sausage", "Pork Sausage", "turkey sausage")
)

non_meats = (
    ("Tofu, Seitan"),           #1
    ("Tempeh"),                 #2
    ("Teturized Vegetable Protein, Lentils, Tempeh"),  #3
    ("Jackfruit"),               #4
    ("Seitan or Tempeh Vegitarian bacon"), #5
    ("Better Than Boullion non-chicken broth (or like brand"),
    ("Better Than Boullion non-beef broth (or like brand"),
    ("Lightlife meatless sausage (or like brand")
)