healthy = (
    ("Canadian bacon", "turkey bacon", "smoked turkey", "lean prosciutto"),
    ("Whole-grain bread"),
    ("Rolled oats", "crushed bran cereal", "ground flax seeds"),
    ("Applesauce"),
    ("cooking spray"),
    ("egg white"),
    ("whole-wheat pastry flour"),
    ("Extra-lean ground beef", "lean ground beef", "ground chicken breast", "ground turkey breast"),
    ("Arugula", "chicory", "collard greens", "kale", "spinach", "watercress"),
    ("Reduced-calorie mayonnaise"),
    ("Evaporated skim milk"),
    ("Reduced fat milk", "skim milk"),
    ("whole-wheat pasta"),
    ("Brown rice", "wild rice"),
    ("Fat free sour cream", "low-fat sour cream", "low-fat plain yogurt", "fat-free plain yogurt", "greek yogurt"),
    ("plain low-fat yogurt"),
    ("stevia"),
    ("cacao nibs"),
    ("coconut oil"),
    ("Fat free cream cheese")
)

not_healthy = (
    ("Bacon"),
    ("white bread"),
    ("Bread crumbs"),
    ("Butter", "margarine"),
    ("greese pan with Butter", "greese pan with margarine"), # combined step w ingredient
    ("Eggs"),
    ("all-purpose flour"),
    ("ground beef"),
    ("iceberg lettuce"),
    ("mayonnaise"),
    ("evaporated milk"),
    ("whole milk"),
    ("pasta"),
    ("white rice"),
    ("sour cream"),
    ("yogurt"),
    ("sugar"),
    ("chocolate chips"),
    ("vegetable oil"),
    ("cream cheese")
)